### ISSUE TITLE
Why are the results so different from the original paper?

### ISSUE THREAD

**Issue by laituan245** [brmson/Sentence-selection#4]
I understand that this work started as an attempt to reproduce [this paper](https://arxiv.org/abs/1412.1632). However, the results reported in that paper are lower than those reported in this repository. Do you know any reasons why that happened?

Thank you.

**Comment by Silvicek** [comment]
Hi, we believe our better results are due to using a newer word embedding model (we used [GloVe](https://nlp.stanford.edu/pubs/glove.pdf)).
